name: 'Test Code with Coverage and Reports'
description: 'Runs some sbt tests and produces cool reports.'

inputs:
  what-to-test:
    description: 'Name of Test Suite(s)'
    required: true
    default: '*'

runs:
    using: "composite"
    
    steps:
    # run tests
    - name: Run tests
      run: |
        echo "############################"
        echo "#      starting test       #"
        echo "############################"
        echo " ${{ inputs.what-to-test }}"
        sbt coverage "testOnly ${{ inputs.what-to-test }}" coverageReport coverageAggregate
        echo "############################"
        echo "#      starting test       #"
        echo "############################"
      shell: bash
